apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-deployment
spec:
  selector:
    matchLabels:
      app: marketplace-k8s-postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: marketplace-k8s-postgresql
    spec:
      containers:
        - name: marketplace-project
          image: marketplace-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgresql  # Nome do serviço do PostgreSQL
            - name: DB_NAME
              value: mydb  # Nome do banco de dados
            - name: DB_USERNAME
              value: admin  # Usuário do banco
            - name: DB_PASSWORD
              value: admin  # Senha do banco
            - name: KEYCLOAK_URL
              value: "http://keycloak:8081"  # URL do Keycloak dentro do Kubernetes
            - name: KEYCLOAK_REALM
              value: "GamerHeaven"  # O nome do seu realm do Keycloak
            - name: KEYCLOAK_CLIENT_ID
              value: "GamerHeaven-app"  # O Client ID no Keycloak
            - name: KEYCLOAK_CLIENT_SECRET
              value: ""  # O Client Secret no Keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: marketplace-svc
spec:
  selector:
    app: marketplace-k8s-postgresql
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
