spring.application.name=marketplace
spring.profiles.active=test
spring.jpa.open-in-view=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/GamerHeaven
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak-service:8081/realms/GamerHeaven/protocol/openid-connect/certs
keycloak.realm=GamerHeaven
keycloak.resource=GamerHeaven-app
keycloak.bearer-only=true